package Module::CoreList::Perl500307;

use strict;
use warnings;

use vars qw[$VERSION $released $version $deprecated];

$VERSION = '5.00307';

$released = '1996-10-10';

$version =
{
"AnyDBM_File"           => undef,
"AutoLoader"            => undef,
"AutoSplit"             => undef,
"Benchmark"             => undef,
"Carp"                  => undef,
"Config"                => undef,
"Cwd"                   => undef,
"DB_File"               => "1.03",
"Devel::SelfStubber"    => "1.01",
"diagnostics"           => undef,
"DirHandle"             => undef,
"DynaLoader"            => "1.00",
"English"               => undef,
"Env"                   => undef,
"Exporter"              => undef,
"ExtUtils::Embed"       => "1.18",
"ExtUtils::Install"     => "1.15 ",
"ExtUtils::Liblist"     => "1.20 ",
"ExtUtils::MakeMaker"   => "5.38",
"ExtUtils::Manifest"    => "1.27",
"ExtUtils::Mkbootstrap" => "1.13 ",
"ExtUtils::Mksymlists"  => "1.12 ",
"ExtUtils::MM_OS2"      => undef,
"ExtUtils::MM_Unix"     => "1.107 ",
"ExtUtils::MM_VMS"      => undef,
"ExtUtils::testlib"     => "1.11 ",
"Fatal"                 => undef,
"Fcntl"                 => "1.00",
"File::Basename"        => "2.4",
"File::CheckTree"       => undef,
"File::Copy"            => "1.5",
"File::Find"            => undef,
"File::Path"            => "1.01",
"FileCache"             => undef,
"FileHandle"            => "1.00",
"FindBin"               => "1.04",
"GDBM_File"             => "1.00",
"Getopt::Long"          => "2.04",
"Getopt::Std"           => undef,
"I18N::Collate"         => undef,
"integer"               => undef,
"IO"                    => undef,
"IO::File"              => "1.05",
"IO::Handle"            => "1.12",
"IO::Pipe"              => "1.07",
"IO::Seekable"          => "1.05",
"IO::Select"            => "1.09",
"IO::Socket"            => "1.13",
"IPC::Open2"            => undef,
"IPC::Open3"            => undef,
"less"                  => undef,
"lib"                   => undef,
"Math::BigFloat"        => undef,
"Math::BigInt"          => undef,
"Math::Complex"         => undef,
"NDBM_File"             => "1.00",
"Net::Ping"             => "1.01",
"ODBM_File"             => "1.00",
"Opcode"                => "1.01",
"ops"                   => undef,
"OS2::ExtAttr"          => "0.01",
"OS2::PrfDB"            => "0.02",
"OS2::Process"          => undef,
"OS2::REXX"             => undef,
"overload"              => undef,
"Pod::Functions"        => undef,
"Pod::Text"             => undef,
"POSIX"                 => "1.00",
"Safe"                  => "2.06",
"SDBM_File"             => "1.00",
"Search::Dict"          => undef,
"SelectSaver"           => undef,
"SelfLoader"            => "1.06",
"Shell"                 => undef,
"sigtrap"               => "1.01",
"Socket"                => "1.5",
"strict"                => undef,
"subs"                  => undef,
"Symbol"                => undef,
"Sys::Hostname"         => undef,
"Sys::Syslog"           => undef,
"Term::Cap"             => undef,
"Term::Complete"        => undef,
"Term::ReadLine"        => undef,
"Test::Harness"         => "1.13",
"Text::Abbrev"          => undef,
"Text::ParseWords"      => undef,
"Text::Soundex"         => undef,
"Text::Tabs"            => "96.051501",
"Text::Wrap"            => "96.041801",
"Tie::Hash"             => undef,
"Tie::Scalar"           => undef,
"Tie::SubstrHash"       => undef,
"Time::Local"           => undef,
"UNIVERSAL"             => undef,
"vars"                  => undef,
"VMS::Filespec"         => undef,
"VMS::Stdio"            => "2.0",
};

1;
